<?php

/**
 * @file
 * Contains d8_custom_form_using_validator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_custom_form_using_validator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the d8_custom_form_using_validator module.
    case 'help.page.d8_custom_form_using_validator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function d8_custom_form_using_validator_theme() {
  return [
    'd8_custom_form_using_validator' => [
      'render element' => 'children',
    ],
  ];
}
